---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: CentOS
    image: centos:7
    image_version: latest
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: goss
  enabled: true
  lint:
    name: yamllint
